language: csharp
sudo: required
mono: none
dotnet: 3.1
solution: Kwekker_AccountService.sln

before_script: 
- dotnet restore  

script: 
- dotnet build ".\Account_Service" -c Release 
- dotnet test ".\Account_Service_Test" -v n

deploy:
  provider: azure_web_apps
  username: KwekkerAccountService\KwekkerUser
  password: Pudace5!
  site: kwekkeraccountservice.azurewebsites.net
  verbose: true
  on:
      branch: dev