#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwekkeraccountservice
spec:
  selector:
    matchLabels:
      app: kwekkeraccountservice
  replicas: 1
  template:
    metadata:
      labels:
        app: kwekkeraccountservice
    spec:
      containers:
        - name: kwekkeraccountservice
          image: stefv013/kwekkeraccountservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 8082
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
